sort/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    path('', views.sorteador, name='sorteador'),
    path('sorteio', views.sorteio, name='sorteio'),
    path('sobre', views.sobre, name='sobre'),
]

sorteador/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sort.urls')),
]

sort/models.py
from django.db import models

# Create your models here.

sort/forms.py
from django import forms


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

    file.widget.attrs.update({'class': 'custom-file-input'})

sort/views.py
#!-*- conding: utf8 -*-
from random import randint

import openpyxl

from django.shortcuts import render
from sort.forms import UploadFileForm


def sorteador(request):
    """
    Renderiza a página inicial e o input file.
    :param request:
    :return:
    """
    form = UploadFileForm()

    return render(request, 'sort/sorteio.html', {'form': form})


def sorteio(request):
    """
    Função que carrega o arquivo xlsx, sorteia uma linha aleatoria e exibe dados das celulas da linha
    :param request:
    :return:
    """
    if "GET" == request.method:
        form = UploadFileForm()

        return render(request, 'sort/sorteio.html', {'form': form})
    else:
        file = request.FILES["file"]
        wb = openpyxl.load_workbook(file)
        folha = wb.get_sheet_names()

        sheetranges = wb[folha[0]]

        numero_linhas = sheetranges.max_row
        linha_aleatoria = randint(2, numero_linhas)

        numero_sorteado = sheetranges['A' + str(linha_aleatoria)].value
        nome_sorteado = sheetranges['B' + str(linha_aleatoria)].value

        return render(request, 'sort/sorteio.html', {'numero': numero_sorteado, 'nome': nome_sorteado})


def sobre(request):

    return render(request, 'sort/sobre.html', {})

sort/templates/sort/base.html
<!doctype html>
{% load static %}
<html lang="pt-br">
<head>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>SorteioPy</title>

</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="./">SorteioPy</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'sobre' %}">Sobre <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" target="_blank" href="https://github.com/iagovirgilio/sorteiopy">Código Fonte</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container-fluid">
    {% block content %}
    {% endblock %}
</div>

{% block scripts %}
<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
{% endblock %}

</body>
</html>

sort/templates/sort/sobre.html
{% extends 'sort/base.html' %}

{% block content %}

{% load static %}

<main role="main" class="container d-flex justify-content-center">

    <h1>PÁGINA EM CONSTRUÇÃO</h1>

</main><!-- /.container -->
{% endblock %}

sort/templates/sort/sorteio.html
{% extends 'sort/base.html' %}

{% block content %}

{% load static %}

<main role="main" class="container d-flex justify-content-center">

    <div class="card" style="width: 100%">
        <div class="card-header">
            Sorteador para arquivos em excel <strong>gratuito!</strong>
        </div>
        <div class="card-body shadow">
            {% if not nome %}
            <h3 class="card-text mb-5">Selecione seu arquivo no formato XLSX</h3>
            {% endif %}
            {% if nome %}
            <h3 class="card-text mb-5" style="color: navy;">Parabéns, {{ numero }} - {{ nome }}! Você ganhou.</h3>
            {% endif %}

            <form action="{% url 'sorteio' %}" class="text-center" method="post" id="form-upload"
                  enctype="multipart/form-data">
                {% csrf_token %}

                {% if not nome %}
                <div class="input-group mb-3">
                    <div class="custom-file">
                        {{ form.file }}
                        <label class="custom-file-label text-left" for="id_file"
                               aria-describedby="inputGroupFileAddon02">Clique aqui para escolher o arquivo</label>
                    </div>
                </div>
                <button class="btn btn-success" type="submit">SORTEAR AGORA</button>
                {% endif %}
            </form>

            {% if nome %}
            <a href="javascript:window.location.reload(true)" class="btn btn-success mb-3 btn-lg btn-block">SORTEAR NOVAMENTE</a>
            <a href="./" class="btn btn-info mb-3 btn-lg btn-block">CARREGAR NOVO ARQUIVO</a>
            {% endif %}

        </div>
    </div>

</main><!-- /.container -->
{% endblock %}